### ISSUE TITLE
There is a very serious issue that (resizeAllModule)

### ISSUE THREAD

**Issue by ilii** [bpmn-io/bpmn-js-nyan#30]
### Steps to Reproduce

1. Modifying the Elements size can reveal this issue

### Expected Behavior

I hope respected Nikku can solve when he has time。
It's easy to spot him

### Environment

- Host (Browser/Node version)
- OS: [e.g. Windows 11]
- Library version:
"bpmn-js-nyan": "^2.2.0",
"bpmn-js": "^17.9.2",
"diagram-js": "^14.9.0",

**Comment by ilii** [comment]
![bpmn-nyan1](https://github.com/user-attachments/assets/31ea1bd3-e240-47ea-8884-d7c2ec10e7ae)
![bpmn-nyan2](https://github.com/user-attachments/assets/ed293db4-4a99-4e24-ad27-89690a539dd9)

**Comment by nikku** [comment]
Very sorry you, I cannot see issue you hint at. Best, and sorry! :cactus:
