### ISSUE TITLE
resizeAllModule bug

### ISSUE THREAD

**Issue by ShadowSpeedy** [bpmn-io/bpmn-js-nyan#5]
when i use resizeAllModule in additionalModules then if i click the SequenceFlow  
error occured in console

![image](https://user-images.githubusercontent.com/28926508/66698378-353d9a00-ed10-11e9-8c1c-5299628d1ad3.png)

```
EventBus.js?8845:377 TypeError: Failed to execute 'setTranslate' on 'SVGTransform': The provided float value is non-finite.
    at transform (SvgTransformUtil.js?9069:16)
    at ResizeHandles._createResizer (ResizeHandles.js?8dec:126)
    at ResizeHandles.createResizer (ResizeHandles.js?8dec:137)
    at ResizeHandles.addResizer (ResizeHandles.js?8dec:163)
    at forEach (index.esm.js?3736:166)
    at eval (ResizeHandles.js?8dec:60)
    at invokeFunction (EventBus.js?8845:509)
    at EventBus._invokeListener (EventBus.js?8845:362)
    at EventBus._invokeListeners (EventBus.js?8845:348)
    at EventBus.fire (EventBus.js?8845:310)
```

**Comment by nikku** [comment]
Please provide a test case that allows us to reproduce this issue. Or, file a PR that fixes it.

**Comment by philippfromme** [comment]
Closing this. Feel free to re-open if you can provide a test or a fix.

**Comment by ShadowSpeedy** [comment]
sorry to reply so late
in diagram-js\lib\features\resize\ResizeHandles.js   line 91
 _createResizer = function(element, x, y, rotation, direction)   when i click SequenceFlow  the parm x, y would be NaN  then the error occured in function "transform" in (diagram-js\lib\util\SvgTransformUtil.js )  

![image](https://user-images.githubusercontent.com/28926508/67265564-99b2e300-f4e0-11e9-8064-4fb0d70802ae.png)
![image](https://user-images.githubusercontent.com/28926508/67265921-7ccadf80-f4e1-11e9-972e-efa50801562b.png)

So I added this Line to  prevent this 
if (x != undefined && y!=undefined && !window.isNaN(x) && !window.isNaN(y))

**Comment by crmarin** [comment]
In file ResizeAllRules.js
`
ResizeAllRules.prototype.init = function () {
  this.addRule('shape.resize', 1500, function (data) {
    if (data.shape.type === 'bpmn:MyType'
      || data.shape.type === 'bpmn:Other'
      || data.shape.type === 'bpmn:TaskX'
    ) {
      return true;
    }
  });
};
`
