### ISSUE TITLE
nyan in Angular

### ISSUE THREAD

**Issue by hosseinjafari24** [bpmn-io/bpmn-js-nyan#6]
__How to use bpmn-js-nyan  In angular 8 ?__
please send me example of plugin

**Comment by nikku** [comment]
Our bug tracker is not the place for your questions. Please ask them [in our forum](https://forum.bpmn.io). When asking a question, be descriptive: What did you try, what did not work out? Where did you get stuck?

Also, please use an existing issue template when you open issues in our repositories:

![image](https://user-images.githubusercontent.com/58601/78544696-d5c1d200-77fa-11ea-8ae6-1cb2936e4e96.png)
