### ISSUE TITLE
点击连线的时候报错～

### ISSUE THREAD

**Issue by Smosar** [bpmn-io/bpmn-js-nyan#8]
当我导入ResizeAllRules 的时候，点击元素之间的线会报错

**Comment by philippfromme** [comment]
Please communicate in English so we can help you.

**Comment by Smosar** [comment]
When I import ResizeAllRules, clicking the line between elements will give an error

**Comment by MaxTru** [comment]
Thanks for reporting. Could you please use the template for a bug and then reopen this issue. We in particular need clear steps to reproduce. Thanks

```
__Describe the Bug__

<!-- A clear and concise description of what the bug is. -->


__Steps to Reproduce__

<!-- Clear steps that allow us to reproduce the error. -->

1. do this
2. do that
3. now this happens


__Expected Behavior__

<!-- A clear and concise description of what you expected to happen. -->


__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

```

**Comment by Smosar** [comment]
ResizeAllRules.prototype.init = function () {

  this.addRule('shape.resize', 1500, function (data) {
    if (data.shape.type !== "bpmn:SequenceFlow") {
      return true;
    }
  });

};
// changed
