### ISSUE TITLE
When exporting the diagram after applying custom colours, the colour is not saved in the export. How to fix?

### ISSUE THREAD

**Issue by vesper8** [bpmn-io/bpmn-js-nyan#9]
I'm only using the `resizeAllModule` and `colorPickerModule` in a real project.

The resizing works great, and when you export a file, it correctly saves the dimensions so that when you load that file again you get the resized diagram.. great

With the colours however, when you export the colour is not exported, so when you load it again the colours are lost.

Can anyone explain what I need to do to ensure that colours can be exported/imported please?

Many thanks!

**Comment by philippfromme** [comment]
How is this related to bpmn-js-nyan?

**Comment by vesper8** [comment]
The two modules in questions are used/introduced in bpmn-js-nyan. That is, this is where I first found them. So I thought it'd be a good place to ask about them.

**Comment by smbea** [comment]
Please use one one of our [existing issue templates](https://github.com/bpmn-io/bpmn-js-color-picker/issues/new/choose). I can transfer the issue to the proper repository once the context is clear.

For help in using our tools, please refer to the [bpmn.io forum](https://forum.bpmn.io/).
